spring:
  datasource:
    name: test
    url: jdbc:mysql://rds19y8d14j0mie1nq57o.mysql.rds.aliyuncs.com:3361/mystudy
    username: my_study
    password: dev_java_mystudy_2017
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: mapper/*
  typeAliasesPackage: com.mytt.boot.Moudel